version: '3'

services:
  management1:
    image: mysql/mysql-cluster
    command: ["ndb_mgmd"]
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./data/management1/:/var/lib/mysql/
    networks:
      mysql:
        ipv4_address: 192.168.0.2
  ndb1:
    image: mysql/mysql-cluster
    command: ["ndbd"]
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./data/ndb1/:/var/lib/mysql/
    depends_on:
      - management1
    networks:
      mysql:
        ipv4_address: 192.168.0.3

  ndb2:
    image: mysql/mysql-cluster
    command: ["ndbd"]
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./data/ndb1/:/var/lib/mysql/
    depends_on:
      - management1
    networks:
      mysql:
        ipv4_address: 192.168.0.4

  mysql1:
    image: mysql/mysql-cluster
    command: ["mysqld"]
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./data/ndb1/:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=onsports
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - management1
      - ndb1
      - ndb2
    networks:
      mysql:
        ipv4_address: 192.168.0.10
networks:
  mysql:
    external:
      name: cluster


  # cluster
